export const SET_APP_LOADED = "App/SET_APP_LOADED";

export const UPDATE_AUTH_FIELD = "App/UPDATE_AUTH_FIELD";

export const REGISTER_USER = "App/REGISTER_USER";
export const REGISTER_USER_SUCCESS = "App/REGISTER_USER_SUCCESSS";
export const REGISTER_USER_FAILURE = "App/REGISTER_USER_FAILURE";

export const LOGIN_USER = "App/LOGIN_USER";
export const LOGIN_USER_SUCCESS = "App/LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "App/LOGIN_USER_FAILURE";

export const LOGOUT_USER = "App/LOGOUT_USER";

export const GET_CURRENT_USER = "App/GET_CURRENT_USER";
export const SET_CURRENT_USER = "App/SET_CURRENT_USER";

export const LIKE_ARTICLE = "App/LIKE_ARTICLE";
export const UNLIKE_ARTICLE = "App/UNLIKE_ARTICLE";
