export const SAVE_USER_PROFILE = "Settings/SAVE_USER_PROFILE";
export const SAVE_USER_PROFILE_SUCCESS = "Settings/SAVE_USER_PROFILE_SUCCESS";
export const SAVE_USER_PROFILE_FAILURE = "Settings/SAVE_USER_PROFILE_FAILURE";
